@echo off
echo Open Watcom Build Environment
SET PATH=d:\WATCOM\BINW;%PATH%
SET PATH=d:\WATCOM\BINNT;%PATH%
SET INCLUDE=d:\WATCOM\H\NT;%INCLUDE%
SET INCLUDE=d:\WATCOM\H\NT;%INCLUDE%
SET INCLUDE=%INCLUDE%;d:\WATCOM\H\NT\DIRECTX
SET INCLUDE=%INCLUDE%;d:\WATCOM\H\NT\DDK
SET INCLUDE=d:\WATCOM\H;%INCLUDE%
SET WATCOM=d:\WATCOM
SET EDPATH=d:\WATCOM\EDDAT
SET WHTMLHELP=d:\WATCOM\BINNT\HELP
SET WIPFC=d:\WATCOM\WIPFC
